apiVersion: falarica.io/v1alpha1
kind: Presto
metadata:
  name: {{ .Release.Name }}-presto
spec:
  service:
    type: "NodePort"
    port: {{ .Values.spec.port }}
    nodePort: {{ .Values.spec.nodeport }}
  catalogs:
    {{- $globpattern := printf "%s/*.cat" .Values.install.name }}
    catalogSpec: {{ range $path, $_ := .Files.Glob $globpattern }}
      - name: {{ base $path | trimSuffix ".cat" }}
        content:
{{ $.Files.Get $path | indent 10 -}}{{ end }}
  volumes:
  - name: {{ .Values.volumes.name }}
    emptyDir: {}
    mountPath: {{ .Values.volumes.dir }}
  coordinator:
    memoryLimit: {{ .Values.coordinator.memory }}
    cpuLimit: {{ .Values.coordinator.cpulimit | quote }}
  worker:
    memoryLimit: {{ .Values.worker.memory }}
    cpuLimit: {{ .Values.worker.cpulimit | quote }}
    count: {{ .Values.worker.count }}
    autoscaling:
      enabled: {{ .Values.worker.autoscale }}
      minReplicas: {{ .Values.worker.minreplicas }}
      maxReplicas: {{ .Values.worker.maxreplicas }}
      targetCPUUtilizationPercentage: {{ .Values.worker.targetcpuutilizationpercentage }}
    additionalProps:
      shutdown.grace-period: {{ .Values.worker.shutdowngraceperiod }}
      spill-enabled: {{ .Values.worker.spillenabled | quote  }}
      spiller-spill-path: {{ .Values.worker.spilldirpath }}
  additionalPrestoPropFiles:
    access-control.properties:
      access-control.name=read-only

