# Default values for presto-gke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

install:
  name: prestotest

spec:
  port: 8100
  nodeport: 30002

catalog:
  catalogname: tpch
  connectorname: tpch

volumes:
  name: spillvol
  dir: /prestospill

coordinator:
  memory: "1Gi"
  cpulimit: "0.5" 

worker:
  memory: "1Gi"
  cpulimit: "0.5"
  count: 1
  autoscale: false
  minreplicas: 2
  maxreplicas: 3
  targetcpuutilizationpercentage: 20
  shutdowngraceperiod: 10s
  spillenabled: "true"
  spilldirpath: "/prestospill"
  
